namespace BandItPlus.BanditRaid
{
    // Distinct named lieutenants of the Bandit King, each with his own encyclopedia backstory.
    // Names[i] pairs with Backstories[i]. Authored via the creative-writing fan-out (draft -> refine).
    // Backstories are verbatim strings (paragraphs separated by blank lines); Backstory(i) normalizes the
    // source line endings to "\n" so the encyclopedia renders clean paragraph breaks.
    public static class BanditLieutenantLore
    {
        public static readonly string[] Names =
        {
            "{=bp_lieutenantlore_001}Garruk the Hound",
            "{=bp_lieutenantlore_002}Sevrin Three-Fingers",
            "{=bp_lieutenantlore_003}Old Maddoc",
            "{=bp_lieutenantlore_004}Hagen Crowfeeder",
            "{=bp_lieutenantlore_005}Yorath Gallows-Born",
            "{=bp_lieutenantlore_006}Vess the Shrike",
        };

        public static string Name(int i)
        {
            if (Names.Length == 0) return "{=bp_lieutenantlore_007}Bandit Lieutenant";
            return Names[((i % Names.Length) + Names.Length) % Names.Length];
        }

        public static string Backstory(int i)
        {
            if (Backstories.Length == 0) return "";
            int idx = ((i % Backstories.Length) + Backstories.Length) % Backstories.Length;
            return Backstories[idx].Replace("\r\n", "\n");
        }

        public static readonly string[] Backstories =
        {
            // 0 — Garruk the Hound
BandItPlus.Localization.Get("bp_lieutenantlore_008", @"They say Garruk was a huntsman once, away in the cold marches where the forest grants no man an easy living. He kept the boar-runs and the deer-paths for a lesser lord, and there was no track laid in mud or frost or wet-rotted leaf that his eye could not read — a hoof half-filled with thaw-water, the white scar where a flank had brushed bark, the bruised stem that told him a beast had passed at dawn and not at dusk. The ruin of him came not by the sword but by debt and a burned steading: a winter that killed the seed corn, a master who hanged Garruk's brother from a roadside oak over a poached stag, and a grave they hacked from ground too frozen to take it, so that the stones had to be heaped on top against the foxes. After that the man went into the trees and did not come out the same. He had learned that what he had done to deer he could do to men, and that men, when they run, leave the richer spoor — they sweat, they weep, they grasp at branches, they look back.

He took the Bandit King's collar without ceremony and without love. Vaykos had no need to break him; he needed only to point. Where another captain swears for plunder or out of fear, Garruk swore because the King's banner gave his hunting a whole country to range across and a warrant no margrave's gallows could reach. The bargain was plain as a set snare. The King names the quarry; the Hound does not ask why, and the King does not ask how. It is the cleanest contract in all that outlaw host, and the most terrible, for there is no clause in it for mercy and no hour appointed for its ending.

It is the fleeing that he is given. When a debtor slips the King's reckoning, when a turncoat carries word down to the lowland lords, when a girl held for ransom climbs from a window and runs barefoot for the tree-line — these are not given to the host. They are handed to Garruk, and the men speak of that handing the way they speak of a door drawn shut in the dark. He goes out alone, or with two silent men who carry no torches, and he does not hurry, for he has learned that the hunted tire first and the hunted sleep worst. He reads the bent grass, the turned stone, the cold ash of a fire smothered too quick; he buries his face in a cloak thrown aside in panic and breathes the sour fear-sweat soaked into the wool until he knows the shape of the one who wore it. He has crossed three valleys and worn the soles from a season's boots after a single man, eating what the wood gave him, and at the end of it the man was found.

What sets the dread of him apart is that there is no hatred in it. A wolf does not hate the hare; it only closes the distance. Garruk will sit across a guttering fire from the one he means to take, break bread with him, speak low and almost kindly of the cold and the long road, and finish it in the grey hour before dawn with no more rancour than a man wringing the neck of a bird caught in a springe. The villages along the marches do not curse his name; they lower their voices when they speak it, as though a loud word might turn his ear toward them. Mothers along those frontiers tell their children that the worst thing in the wood is not the beast that roars and shows its teeth, but the thing that makes no sound and does not tire and is always, always nearer than it was.

Among Vaykos's captains he is the one the others will not cheat, for every man of them has done the cold arithmetic. A traitor may flee the King's wrath and win himself a head start of days, of weeks, of a whole frozen mountain range. It will never be enough. Somewhere far behind, unhurried and unhating, the Hound has already knelt to the first print and pressed two fingers to its cooling edge — and the Hound, in all the years men have feared him, has never once been called off."),

            // 1 — Sevrin Three-Fingers
BandItPlus.Localization.Get("bp_lieutenantlore_009", @"Before the name went sour he was only Sevrin of the Ortwell shambles, a butcher's boy who knew the seams of a carcass before he knew his letters. He never did learn his letters. What he learned, hock-deep in offal and the cold copper stink of the killing-floor, was that a body keeps the same grammar whether it walks on two legs or four: the joint that wants to open, the soft place under the short ribs where the steel slides in without argument, the tendon that, parted, drops a thing where it stands. He might have grown old at the block, fat on lights and small thieving, had his fingers not strayed once into another man's purse and his luck not strayed with the magistrate's patience.

They did not hang him. Hanging is a kindness kept for men with kin to do the weeping. Instead the magistrate's man pressed Sevrin's left hand flat to the very block he had worked since he was a boy — the wood black and sweet with twenty years of blood — and took two fingers with a butcher's cleaver, slow, in two strokes, so the lesson would carry weight. The smallest, and the one that leaned against it. He was made to thank the court before they suffered him to crawl into the gutter and bleed.

He did not die of it, though the stumps wept and greened and a whole winter found him shivering in a doorway, teaching a ruined hand to break bread and open throats with three fingers and a thumb. That winter gave him the thing the magistrate had never thought to give: a whole hand, he came to understand, is a lazy hand. A man with all his fingers grips like a frightened fool, all knuckle and no thought, and shouts every stroke before it lands. Sevrin, robbed of the fist, had to keep the knife as a balanced thing and not a clenched one — held light, pinched between thumb and the two fingers the cleaver had spared, so the blade lay in his palm like a second tongue and spoke before the eye could read its lips. Come the thaw he killed three men. Not one of them saw the steel before it was already warm inside him.

Word of such a man runs the low roads faster than any herald's horn, and it was on the low roads that the Bandit King's reavers came upon him. They did not press him into Vaykos's host. They asked him, which is its own black species of dread. Sevrin took the collar gladly. A throne of mud is a throne still, and beneath the King a man of his peculiar craft need never again kneel snivelling before a magistrate. He had thanked the court once. Kneeling in the King's firelight he swore he would thank no man living ever again, and he keeps the oath by leaving the thanking to others.

In the host he breaches no wall, roars at the head of no charge. Sevrin is the quiet errand, the knife sent on ahead. Where the King would have a sentry gone, a tollman made reasonable, a rival lieutenant found cold in his blankets with no wound any surgeon can name, it is Sevrin who comes soft-shod through the dark and goes out the same way, the straw undisturbed behind him. The two taken fingers he kept; bone now, scraped and yellowed, strung on a cord at his throat. He is known to set them on the board during a parley, just so, where the other man's eye cannot leave them, and he says nothing of them at all. He has no need. The threat is the sum every captive works out alone in the dark: here is a man the law unmade and the cold did not finish, who came back from both the keener for it — and whatever the cleaver left undone, the three fingers it spared will see to themselves."),

            // 2 — Old Maddoc
BandItPlus.Localization.Get("bp_lieutenantlore_010", @"No man living recalls Maddoc young. The chroniclers of the river-towns set his name down two reigns past and already wrote it the way the marches say it now — Old Maddoc, as though he had come into the world grey and scarred and waiting. The truth, what little has survived the burying of it, is plainer and worse. He was a hearth-soldier once, swordhand to some thin-pursed lord of the marches whose name the dust has long since eaten, and when that house went down in a winter campaign no living tongue remembers, Maddoc walked out of the burning hall with embers in his beard and three other men at his back. He put all three in the cold ground before the thaw broke. He has been digging graves ever since. Not once has he been the man laid in one.

They reckon him sixty, and reckon like fools. No body carries the tally of hurts he carries on sixty winters alone; the count is written too deep, in too many hands. Every span of him is a ledger kept in scar. The white seam that splits brow from jaw where an axe swung a finger's width too wide. The two stiff fingers that will not close to a fist in any weather. The bitten notch in his ear, the puckered glaze of an old burn riding one forearm, the limp that wakes only when the frost comes down. He does not speak of them, nor finger them by the fire as lesser men finger their wounds for an audience. He stopped hating the men who dealt them long ago, for every last one of those men is under the sod, and Maddoc is not, and he holds that this settles the whole of the matter and wants no further word spent on it.

He took the King's collar the way a grey hound takes the warm side of the hearth — without illusion and without gratitude, for the shelter of it, because the road behind him ended in a ditch and Maddoc had decided, somewhere across the long years, that he would not die in one. Vaykos does not own Maddoc's love. Little reaches that far down in him now; the years have silted it over. But the King gives bread, and a fire that does not gutter, and a fresh crop of young men to outlive, and in return Maddoc gives the host the one thing a band of brigands most wants and least possesses — a memory. He knows which fords drown a man in the spring melt, which lords pay the agreed coin and which sell you to the gibbet, which ambush was sprung on this very hillside in a harder winter and whose blood it was that froze in the ruts come morning. He is the host's grey conscience, and the King prizes him above three captains who can swing a heavier arm.

He serves by waiting. While the hot-blooded ride whooping down into the killing, Old Maddoc holds the rear with a fist of the steadiest throat-cutters in the host, and it is from that patient back rank, and not from the screaming van, that the slaughter is truly governed — the line that does not buckle, the flankers ridden down in the wheatfield before ever they reach the road, the captive kept breathing because Maddoc, and no other eye among them, weighed what he was worth alive. Young raiders come to dread his silence sooner than another man's roaring. A captain who bellows can be read and got round. Maddoc only watches, slow and unblinking, and the watching speaks plain as a sentence read out: I have seen your kind a hundred times over, boy, and I have shovelled every one of them under the dirt. Do not make me dig the hundred-and-first.

That is the dread he throws — not the white heat of a killer in his prime, but the cold arithmetic of a man who has buried everyone. There is no proving yourself to him, no name loud enough to move him, no defiance he has not already stood over and outlasted. The marches whisper it low at the fireside: Old Maddoc does not kill in anger and does not kill in haste. He outlives. And the dying is left to come along behind, in its own time, as it always has, as it always will."),

            // 3 — Hagen Crowfeeder
BandItPlus.Localization.Get("bp_lieutenantlore_011", @"They named him Hagen at a font in the marches of Battania, a freeholder's son with three brothers and a strip of barley to his family's name. The Mappa Mundi remembers none of that. What it remembers is the year the levy came through and pressed the brothers into a border war no chronicle troubled to win, and left the boy to bury what the dogs and the ravens had not already taken. Nine days he laboured at it, they say. By the ninth he had set down the spade. He had learned the lesson no priest would teach him: that the earth is greedy and slow to close its mouth, but the birds are punctual, and they ask for nothing in return but patience.

Why he took the King's collar is told plainly enough. There is no acre left to a man who will not stoop his back, and Hagen would not stoop. He came to Vaykos already half a legend in the wrong fashion — a brigand who had fought the petty lords' bailiffs to a standstill in the Cuthrey thickets and burned the assize rolls in the ditch after, so that no parchment in the realm could any longer name him. The Bandit King keeps a use for the man other men will not stand shoulder to shoulder beside, and he gave Hagen a column and asked of it only two things: that it move, and that it be feared. Both Hagen has answered past the reckoning of any lieutenant under the black banner.

He serves by what he forbids. Where lesser captains strip the slain and leave the gleaning to the village widows, Hagen suffers no grave to be dug — not for the enemy, not for his own, for the crow draws no line between a kinsman and a foe, and neither, he says, should the living. A field he has crossed lies black by the second morning, the stubble crawling with wings, the wind off it gone thick and sweetish and loud with that wet tearing croak that does not cease from dawn to dark. And the host that feeds there does not scatter when he strikes his camp and marches on. It rises with him. It hangs above the column in a slow turning smoke of feathers, gorged and unhurried, and comes after. They have learned the tramp of his men the way a hound learns the note of its master's horn.

So the dread of him arrives before his vanguard, borne in on the wing. A watchman on a tower marks the crows kettling over the eastern road before ever he marks a single horse, and he understands, and the bell he hauls upon is less an alarm than a dirge. Towns have thrown open their gates to the rumour of feathers, the elders coming out grey and shaking with the keys before a spear was so much as levelled. He need not raise his standard; the sky raises it for him, restless and patient and black, wheeling above a man who has made of the battlefield's aftermath a thing as certain as the fall of night. Crowfeeder they call him, for the plain reason any child could give — and for a quieter one the old men only whisper: that the feeding was never the leavings of his war, but the whole purpose of it. The carrion is the one tithe Calradia ever paid him, and the one he means to go on collecting until there is no hand left to deny it."),

            // 4 — Yorath Gallows-Born
BandItPlus.Localization.Get("bp_lieutenantlore_012", @"They hanged him at the crossroads above Garios on a grey morning thick with wet rope and crow-dung, and by every law of God and gallows the drop should have ended the matter. He had been a debt-man once, a swineherd's son who put a billhook through a tax-reeve's eye over the price of a stolen sow, and the verdict took less time than the digging of the grave nobody troubled to dig. But the hemp was rotten and the knot was a coward's knot, tied loose by a hangman in a hurry to be out of the cold. When they hauled the cart from under him he swung, and kicked, and the rope groaned twice and parted at the third jolt, and dropped him choking into the churned black mud beneath his own dangling shadow. The reeve's men, who had laughed through the reading of the charge, did not laugh then. They saw a hanged man on his knees in the muck with his face gone purple-black and his tongue thick between his teeth and his eyes full of the long road that runs out past the edge of dying, and they dropped their pikes and ran. He knelt there while his heart remembered its work and the frost crept up through his knees, and then he stood, and then he walked, and he has been walking ever since with the rope's white kiss seared across his throat.

The scar never faded. It rides the column of his neck like a second mouth sewn shut, a pale rope-weal the breadth of a thumb, puckered and shining where the hemp burned through the skin, and he neither hides it beneath cloth nor boasts of it in his cups; he simply wears it, and lets men's eyes crawl to it the way eyes crawl to an open wound. Vaykos found him in a winter byre near the Heth marches, sitting alone among frozen cattle in the blue dark, too poor to be worth robbing and too strange to be worth the trouble of killing. The Bandit King asked him what he wanted of this world. Yorath answered, in the flat ruined whisper the rope had left him, that he wanted nothing at all — having already been stripped of the one thing a man clutches hardest, and found in the losing that it had cost him very little. Vaykos, who hoards the fearless the way a miser hoards clipped coin, gave him a fist of cutthroats and a black stretch of road, and asked no oath of him. A man who cannot be threatened cannot be bound, and so Yorath is held to the King by nothing in this world but his own dry, gallows humour.

He goes at the front of every storming, where the rope-shy and the praying hang back in the smoke. Yorath Gallows-Born walks into spear-hedges and burning doorways with the slow, unhurried gait of a man crossing his own yard at dusk, for the worst this world keeps in its cellar was already poured out over him on a wet morning above Garios, and the world has nothing left in its hands to show him. His own captains have watched him take a crossbow bolt through the meat of the shoulder and not so much as shorten his stride; watched him stand in a falling hail of arrows, head tipped back, laughing that cracked and breathless laugh, while better men clawed at the dirt for cover. They have stopped calling it courage. Courage is the mastering of fear, and there is no fear left in Yorath for the mastering — it died with him in the mud, and only the body climbed back out.

He keeps the frayed end of the hanging-rope coiled at his belt, blackened stiff with old Garios mud, and he lays it across the chest of any man who kneels and begs him for his life. To the doomed of three provinces that scrap of hemp is worse than any drawn blade, for the rope says plainly what his ruined voice will not: that he has knelt where they kneel now, that he has gone down the road they so fear to walk, and that it held nothing — nothing — he could not outlast. Mothers along the Hethrun hush their children with his name in the dark, and the hushing does no good, for a child may be frightened by a man who might yet be killed, and every soul on that river has come to know that this one already has been, and walked back, and is coming still."),

            // 5 — Vess the Shrike
BandItPlus.Localization.Get("bp_lieutenantlore_013", @"Before the road from Pellamys to the river fords learned to dread his sign, Vess was no one — a thornland fowler's son, a netter of birds in the brackish marshes where the empire's writ frayed away to mud and reed. They say his father kept a shrike pinned in a willow cage and taught the boy its trade: how the butcher-bird, lacking the talons to hold what it slays, drives its prey down upon the blackthorn and the snapped branch — larder and gibbet in one — so the small dead hang in the cold to be eaten at the bird's leisure. The boy crouched in the frost-stiff sedge and watched the impaled voles go grey and rigid on the spines, and there he learned the lesson beneath the lesson: it is not the killing that masters a country, but the showing of it. A corpse seen is worth a hundred unseen.

His own ruin came in the year the tax-farmers fired the marsh villages for arrears no fowler's coin could ever cover. Vess walked out of the smoke with nothing left to him but the willow cage and a notched billhook, the reek of his burning home grey in his hair, and what the flames had stripped from him he swore to strip from every traveller still rich enough to lose it. For a season he hunted the roads alone, and the watch of three towns set a price upon a man none of them had ever glimpsed — only his handiwork, only the cold and careful things he left arranged behind him.

When Vaykos came east with his outlaw host, he did not trouble to break Vess to the collar; there was nothing in the man left to break. He had only to offer him the open road and a wider larder. The Bandit King gathers wolves and madmen and soldiers gone to rot, but in the Shrike he found a rarer creature — one who grasped that two hundred swords can hold a province of thousands, if the thousands are taught afresh each grey dawn what waits for the disobedient. So Vaykos gave him the toll-roads and the river crossings, and asked of him one thing only: that they stay quiet.

They stay quiet. Where Vess keeps the King's peace the caravans pay without a word of haggling and the headmen send their tithes unbidden, for the marches he holds are hedged about with his sign. A tax-collector lashed to a wayside oak, his ledgers stuffed sodden into his mouth, the ink run down his chin like black bile. A deserter set high in a leafless poplar, hung just so — within reach of the carrion crows, beyond the reach of any pity from the road below, which cannot raise its eyes to him and cannot look away. He does not hide his dead. He plants them. At the milestone, at the well, at the bend where the bride's cart must slow to pass — each one set with a fowler's unhurried patience, turned to the light so the living may read the warning whole and carry it home unbidden in their bellies. A village that has once seen the Shrike's hedge need never be raided twice.

Men say you come to know his country before you ever learn his name — by a sweetness on the wind that thickens as you ride, by the long silence of birds that will not nest where he has passed. He kills few, by the grim arithmetic of his trade; he has no need to kill many. One body, rightly hung, does the labour of a hundred blades. And Vess the Shrike keeps all the patience of the bird whose name he wears, content to wait still as deadwood in the thorn while a whole province, with no further teaching, learns of its own slow accord to be afraid."),
        };
    }
}
