using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using HarmonyLib;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Encounters;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.MountAndBlade;

namespace BandItPlus.Patches
{
    // v207 (2026-05-31) — TEMPORARY diagnostic v2.
    //
    // v206 (yesterday) used TargetMethod() with hard-coded names:
    //   Campaign.OnBeforeSave / CampaignBehaviorManager.OnSave / MBSaveLoad.SaveAs
    // All three resolved to null in the user's game build (v1.4.1 Naval DLC),
    // so the patch never attached and the save exception was never captured.
    // Per memory feedback_bannerlord_harmony_attach_log, this is the classic
    // "guessed method name silently no-ops" failure mode.
    //
    // v207 fixes both problems in one shot:
    //
    //   1. Prepare() ENUMERATES every public+nonpublic method on each candidate
    //      type and writes the full inventory to the BP debug log. That gives
    //      us ground-truth method names for the user's game build, even if our
    //      broad attach below misses the right one.
    //
    //   2. TargetMethods() (plural — Harmony will create one patch per returned
    //      method) attaches to EVERY method on the candidate types whose name
    //      contains "Save" or "Sync" or starts with "OnBefore". That's a wide
    //      net — guaranteed to cover the real save entry point under any
    //      naming convention TaleWorlds chose for v1.4.1.
    //
    //   3. Prefix() and Finalizer() take an extra `MethodBase __originalMethod`
    //      parameter — Harmony injects the method we actually attached to, so
    //      every log line says WHICH method fired. We learn the real save path
    //      from the very first save attempt.
    //
    // All output prefixed "SAVEDIAG:" for grep. REMOVE AFTER ROOT-CAUSE FOUND.
    // Auto-attached by Harmony.PatchAll() in SubModuleClassEntry.
    [HarmonyPatch]
    public static class SaveDiagnosticPatch
    {
        private static readonly string LogPath = BandItPlus.Diagnostics.BpDiag.P("bp_peace_debug.log");

        // Set true once Prepare() has dumped the inventory, to avoid spamming
        // the log if Harmony probes Prepare more than once.
        private static bool _inventoryDumped;

        // v209: dedupe Prefix/"finished cleanly" log lines to first call per
        // method. ~30 attach points × dozens of save attempts = log flood
        // without this. Exceptions still log every time.
        private static readonly HashSet<string> _seenMethods = new HashSet<string>();

        // ---- Target resolution -------------------------------------------------

        // Returns every method on Campaign / CampaignBehaviorManager / MBSaveLoad
        // whose name looks save-related. Harmony attaches one patch per method.
        public static IEnumerable<MethodBase> TargetMethods()
        {
            var results = new List<MethodBase>();

            var campaign      = AccessTools.TypeByName("TaleWorlds.CampaignSystem.Campaign");
            var cbm           = AccessTools.TypeByName("TaleWorlds.CampaignSystem.CampaignBehaviors.CampaignBehaviorManager");

            // v209: confirmed save-pipeline classes via v208 AssemblyWalk —
            // these are the real entry / driver / writer classes for v1.4.1.
            // Patch ALL their non-special methods (broad attach, no name filter)
            // because every method on these save-focused classes is save-related.
            var saveHandler       = AccessTools.TypeByName("TaleWorlds.CampaignSystem.SaveHandler");
            var autoGenCampSave   = AccessTools.TypeByName("TaleWorlds.CampaignSystem.AutoGeneratedSaveManager");
            var saveSysSaveMgr    = AccessTools.TypeByName("TaleWorlds.SaveSystem.SaveManager");
            var saveSysAutoGen    = AccessTools.TypeByName("TaleWorlds.SaveSystem.AutoGeneratedSaveManager");
            var asyncFileDriver   = AccessTools.TypeByName("TaleWorlds.SaveSystem.AsyncFileSaveDriver");
            var fileDriver        = AccessTools.TypeByName("TaleWorlds.SaveSystem.FileDriver");

            // Name-filtered attach for types with lots of unrelated methods
            if (campaign != null) AddMatchingMethods(campaign, results, "Campaign");
            if (cbm      != null) AddMatchingMethods(cbm,      results, "CampaignBehaviorManager");

            // Broad attach for save-focused types — every method is save-relevant
            if (saveHandler     != null) AddAllNonSpecialMethods(saveHandler,     results, "CampaignSystem.SaveHandler");
            if (autoGenCampSave != null) AddAllNonSpecialMethods(autoGenCampSave, results, "CampaignSystem.AutoGeneratedSaveManager");
            if (saveSysSaveMgr  != null) AddAllNonSpecialMethods(saveSysSaveMgr,  results, "SaveSystem.SaveManager");
            if (saveSysAutoGen  != null) AddAllNonSpecialMethods(saveSysAutoGen,  results, "SaveSystem.AutoGeneratedSaveManager");
            if (asyncFileDriver != null) AddAllNonSpecialMethods(asyncFileDriver, results, "SaveSystem.AsyncFileSaveDriver");
            if (fileDriver      != null) AddAllNonSpecialMethods(fileDriver,      results, "SaveSystem.FileDriver");

            SafeWrite("SAVEDIAG: TargetMethods returning " + results.Count + " attach point(s)");
            foreach (var m in results)
            {
                SafeWrite("SAVEDIAG:   attach -> "
                    + (m.DeclaringType?.FullName ?? "?")
                    + "." + m.Name
                    + "(" + ParamSig(m) + ")");
            }

            return results;
        }

        // ---- Prepare: dump method inventory of every candidate type -----------
        public static bool Prepare()
        {
            try
            {
                if (!_inventoryDumped)
                {
                    _inventoryDumped = true;
                    DumpInventory("TaleWorlds.CampaignSystem.Campaign");
                    DumpInventory("TaleWorlds.CampaignSystem.CampaignBehaviors.CampaignBehaviorManager");
                    DumpInventory("TaleWorlds.MountAndBlade.MBSaveLoad");
                    // v208: new namespace candidates + assembly-wide save-type discovery
                    // v208 confirmed these are TYPE NOT FOUND — keep as a marker.
                    DumpInventory("TaleWorlds.SaveSystem.MBSaveLoad");
                    DumpInventory("TaleWorlds.SaveSystem.SaveHandler");
                    DumpInventory("TaleWorlds.SaveSystem.SaveDriver");
                    DumpAllSaveTypesInAllAssemblies();
                    // v209: the real v1.4.1 save-pipeline types discovered above
                    DumpInventory("TaleWorlds.CampaignSystem.SaveHandler");
                    DumpInventory("TaleWorlds.CampaignSystem.AutoGeneratedSaveManager");
                    DumpInventory("TaleWorlds.SaveSystem.SaveManager");
                    DumpInventory("TaleWorlds.SaveSystem.AutoGeneratedSaveManager");
                    DumpInventory("TaleWorlds.SaveSystem.AsyncFileSaveDriver");
                    DumpInventory("TaleWorlds.SaveSystem.FileDriver");
                }
            }
            catch (Exception ex)
            {
                SafeWrite("SAVEDIAG: Prepare inventory dump failed: " + ex.GetType().Name + ": " + ex.Message);
            }

            // Return true unconditionally — even if TargetMethods returns an
            // empty list, we want the inventory dump recorded so we have
            // evidence to act on. Harmony handles empty target lists gracefully.
            return true;
        }

        // ---- Prefix: snapshot state BEFORE save (deduped) ---------------------
        // v209: only log + snapshot the FIRST call per method per session, to
        // avoid log flood now that we attach to ~30 methods. The state at the
        // first call is what we need; subsequent identical calls just confirm
        // the method ran.
        // v210: capture __args every call; OnSaveEnded / OnSaveCompleted are
        // exempt from dedupe so every save-failure event is logged with its
        // success-flag + failure-message string.
        public static void Prefix(MethodBase __originalMethod, object[] __args)
        {
            string m = MethodLabel(__originalMethod);
            try
            {
                string methodName = __originalMethod != null ? __originalMethod.Name : "";
                bool noDedupe = methodName == "OnSaveEnded" || methodName == "OnSaveCompleted";

                bool firstTime;
                lock (_seenMethods)
                {
                    firstTime = _seenMethods.Add("Prefix:" + m);
                }

                if (noDedupe)
                {
                    // v210: every call logged for save-end / save-completed events
                    SafeWrite("SAVEDIAG: " + m + " called (no-dedupe) args: " + FormatArgs(__args));
                    if (firstTime)
                    {
                        LogStateSnapshot("PRE-CALL " + m);
                    }
                }
                else if (firstTime)
                {
                    SafeWrite("SAVEDIAG: PRE-CALL   (via " + m + ")");
                    SafeWrite("SAVEDIAG:   args: " + FormatArgs(__args));
                    LogStateSnapshot("PRE-CALL " + m);
                }
            }
            catch (Exception ex)
            {
                SafeWrite("SAVEDIAG: Prefix snapshot threw at " + m + ": " + ex.GetType().Name + " : " + ex.Message);
            }
        }

        // ---- Finalizer: capture exception, RETURN it unchanged ----------------
        // v210: __args is now injected so we see the post-call arg state (in
        // case the target mutated by-ref params). __result is NOT injected —
        // Harmony silently drops patches when __result is requested on void-
        // returning methods, which would have nuked 412 attach points (caught
        // by the v210 adversarial verifier pass).
        public static Exception Finalizer(Exception __exception, MethodBase __originalMethod, object[] __args)
        {
            string m = MethodLabel(__originalMethod);
            try
            {
                if (__exception == null)
                {
                    // v209: dedupe — clean completions only log first time per method
                    // v210: OnSaveEnded / OnSaveCompleted bypass dedupe so every
                    // success/failure outcome is captured.
                    string methodName = __originalMethod != null ? __originalMethod.Name : "";
                    bool noDedupe = methodName == "OnSaveEnded" || methodName == "OnSaveCompleted";

                    bool firstClean;
                    lock (_seenMethods)
                    {
                        firstClean = _seenMethods.Add("Clean:" + m);
                    }
                    if (firstClean || noDedupe)
                    {
                        SafeWrite("SAVEDIAG: " + m + " first-cleanly-completed");
                        SafeWrite("SAVEDIAG:   final args: " + FormatArgs(__args));
                    }
                }
                else
                {
                    SafeWrite("SAVEDIAG: " + m + " threw "
                        + __exception.GetType().FullName
                        + " : " + (__exception.Message ?? "(no message)"));

                    var inner = __exception.InnerException;
                    int depth = 1;
                    while (inner != null && depth < 6)
                    {
                        SafeWrite("SAVEDIAG:   inner[" + depth + "] "
                            + inner.GetType().FullName
                            + " : " + (inner.Message ?? "(no message)"));
                        inner = inner.InnerException;
                        depth++;
                    }

                    var stack = __exception.StackTrace ?? "(no stack)";
                    SafeWrite("SAVEDIAG:   stack:" + Environment.NewLine + stack);
                }
            }
            catch (Exception logEx)
            {
                SafeWrite("SAVEDIAG: Finalizer logging itself threw at " + m + ": "
                    + logEx.GetType().Name + " : " + logEx.Message);
            }
            return __exception; // re-throw unchanged
        }

        // ---- v210: arg formatting helper --------------------------------------
        // FormatArgs renders an injected __args array as a comma-separated
        // "TypeName=Value" list. Each item's ToString is truncated to 200 chars
        // to keep the log readable. ToString itself is wrapped in try/catch
        // because some objects (lazy proxies, disposed handles, etc.) throw.
        private const int ArgValueTruncLen = 200;

        private static string FormatArgs(object[] args)
        {
            try
            {
                if (args == null) return "(null args)";
                if (args.Length == 0) return "()";
                var sb = new System.Text.StringBuilder();
                for (int i = 0; i < args.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    var a = args[i];
                    if (a == null) { sb.Append("null"); continue; }
                    string typeName;
                    try { typeName = a.GetType().Name; }
                    catch { typeName = "?"; }
                    string val;
                    try { val = a.ToString() ?? "(null)"; }
                    catch (Exception ex) { val = "<ToString threw " + ex.GetType().Name + ">"; }
                    if (val.Length > ArgValueTruncLen) val = val.Substring(0, ArgValueTruncLen) + "…(trunc)";
                    sb.Append(typeName).Append("=").Append(val);
                }
                return sb.ToString();
            }
            catch (Exception ex)
            {
                return "<FormatArgs threw " + ex.GetType().Name + ": " + ex.Message + ">";
            }
        }

        // ---- Shared helpers ---------------------------------------------------

        // v209: attach to EVERY non-special, non-generic method on a save-focused
        // type. Used for SaveHandler, AutoGeneratedSaveManager, SaveManager,
        // AsyncFileSaveDriver, FileDriver — classes where every method is save-
        // related so name-filtering would just miss methods like Write/Flush/
        // Initialize/Dispose that don't contain "Save" but ARE on the save path.
        private static void AddAllNonSpecialMethods(Type type, List<MethodBase> into, string label)
        {
            int before = into.Count;
            var seen = new HashSet<string>(); // dedupe overloads if Harmony struggles
            foreach (var m in type.GetMethods(BindingFlags.Public | BindingFlags.NonPublic
                                              | BindingFlags.Instance | BindingFlags.Static
                                              | BindingFlags.DeclaredOnly))
            {
                if (m.IsSpecialName) continue;
                if (m.IsGenericMethodDefinition) continue;
                // Skip Object methods that may have leaked through DeclaredOnly noise
                if (m.Name == "ToString" || m.Name == "GetHashCode" || m.Name == "Equals") continue;
                // Skip method names that are clearly not save-pipeline (defensive)
                if (m.Name == "Finalize") continue;
                if (!seen.Add(m.Name + "(" + ParamSig(m) + ")")) continue;
                into.Add(m);
            }
            SafeWrite("SAVEDIAG: AddAllNonSpecialMethods(" + label + ") picked " + (into.Count - before));
        }

        private static void AddMatchingMethods(Type type, List<MethodBase> into, string label)
        {
            int before = into.Count;
            foreach (var m in type.GetMethods(BindingFlags.Public | BindingFlags.NonPublic
                                              | BindingFlags.Instance | BindingFlags.Static
                                              | BindingFlags.DeclaredOnly))
            {
                string n = m.Name;
                if (n.IndexOf("Save", StringComparison.Ordinal) >= 0
                    || n.IndexOf("Sync", StringComparison.Ordinal) >= 0
                    || n.StartsWith("OnBefore", StringComparison.Ordinal))
                {
                    if (m.IsSpecialName) continue;
                    if (m.IsGenericMethodDefinition) continue;
                    into.Add(m);
                }
            }
            SafeWrite("SAVEDIAG: AddMatchingMethods(" + label + ") picked " + (into.Count - before));
        }

        // v208: walks every loaded TaleWorlds.* assembly and dumps every type
        // whose FullName contains "Save". Definitive discovery of where the
        // save pipeline lives in the user's game build — v1.4.1 moved many
        // types out of TaleWorlds.MountAndBlade into TaleWorlds.SaveSystem,
        // and the v207 dump proved our hardcoded MountAndBlade.MBSaveLoad
        // lookup returned null. This walk tells us WHERE to look next.
        //
        // ReflectionTypeLoadException is common for partially-loadable assemblies;
        // we recover the partial Types[] (with nulls) instead of bailing.
        private static void DumpAllSaveTypesInAllAssemblies()
        {
            try
            {
                SafeWrite("SAVEDIAG: AssemblyWalk START");
                int totalFound = 0;
                foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
                {
                    string asmName = "(unknown)";
                    try { asmName = asm.GetName().Name; } catch { }
                    if (!asmName.StartsWith("TaleWorlds.", StringComparison.Ordinal)) continue;

                    Type[] types = null;
                    try { types = asm.GetTypes(); }
                    catch (ReflectionTypeLoadException tlex) { types = tlex.Types; }
                    catch { continue; }
                    if (types == null) continue;

                    int perAsm = 0;
                    foreach (var t in types)
                    {
                        if (t == null) continue;
                        string fn = null;
                        try { fn = t.FullName; } catch { continue; }
                        if (string.IsNullOrEmpty(fn)) continue;
                        if (fn.IndexOf("Save", StringComparison.Ordinal) < 0) continue;
                        // Filter UI noise.
                        if (fn.IndexOf("Button", StringComparison.Ordinal) >= 0) continue;
                        if (fn.IndexOf("Icon", StringComparison.Ordinal) >= 0) continue;
                        SafeWrite("SAVEDIAG: AssemblyType[" + asmName + "] " + fn);
                        perAsm++;
                        totalFound++;
                    }
                    if (perAsm > 0)
                        SafeWrite("SAVEDIAG: AssemblyWalk " + asmName + " save-types=" + perAsm);
                }
                SafeWrite("SAVEDIAG: AssemblyWalk END total=" + totalFound);
            }
            catch (Exception ex)
            {
                SafeWrite("SAVEDIAG: AssemblyWalk failed: " + ex.GetType().Name + ": " + ex.Message);
            }
        }

        private static void DumpInventory(string typeName)
        {
            try
            {
                var t = AccessTools.TypeByName(typeName);
                if (t == null)
                {
                    SafeWrite("SAVEDIAG: Inventory[" + typeName + "] = TYPE NOT FOUND");
                    return;
                }

                int n = 0;
                foreach (var m in t.GetMethods(BindingFlags.Public | BindingFlags.NonPublic
                                                | BindingFlags.Instance | BindingFlags.Static
                                                | BindingFlags.DeclaredOnly))
                {
                    if (m.IsSpecialName) continue;
                    n++;
                    SafeWrite("SAVEDIAG: Inventory[" + t.Name + "] "
                        + (m.IsStatic ? "static " : "")
                        + (m.IsPublic ? "pub " : "nonpub ")
                        + m.Name + "(" + ParamSig(m) + ")");
                }
                SafeWrite("SAVEDIAG: Inventory[" + t.Name + "] TOTAL = " + n + " methods");
            }
            catch (Exception ex)
            {
                SafeWrite("SAVEDIAG: Inventory[" + typeName + "] FAILED: "
                    + ex.GetType().Name + ": " + ex.Message);
            }
        }

        private static string ParamSig(MethodBase m)
        {
            try
            {
                var sb = new System.Text.StringBuilder();
                var first = true;
                foreach (var p in m.GetParameters())
                {
                    if (!first) sb.Append(", ");
                    first = false;
                    sb.Append(p.ParameterType?.Name ?? "?");
                }
                return sb.ToString();
            }
            catch { return "?"; }
        }

        private static string MethodLabel(MethodBase m)
        {
            if (m == null) return "(unknown method)";
            return (m.DeclaringType?.Name ?? "?") + "." + m.Name;
        }

        internal static void SafeWrite(string msg)
        {
            try
            {
                File.AppendAllText(LogPath,
                    "[" + DateTime.Now.ToString("HH:mm:ss.fff") + "] "
                    + msg + Environment.NewLine);
            }
            catch { }
        }

        internal static void LogStateSnapshot(string phase)
        {
            string encName = "(null)";
            string locEncName = "(null)";
            string missionName = "(null)";
            string missionMode = "(null)";
            string partySettle = "(null)";
            string currentSettle = "(null)";
            string gameStarted = "(null)";

            try
            {
                var enc = PlayerEncounter.Current;
                if (enc != null)
                {
                    encName = enc.GetType().Name;
                    try
                    {
                        var le = PlayerEncounter.LocationEncounter;
                        if (le != null) locEncName = le.GetType().Name;
                    }
                    catch (Exception ex)
                    { locEncName = "<threw " + ex.GetType().Name + ">"; }
                }
            }
            catch (Exception ex)
            { encName = "<threw " + ex.GetType().Name + ">"; }

            try
            {
                var m = Mission.Current;
                if (m != null)
                {
                    missionName = m.GetType().Name;
                    try { missionMode = m.Mode.ToString(); }
                    catch (Exception ex) { missionMode = "<threw " + ex.GetType().Name + ">"; }
                }
            }
            catch (Exception ex)
            { missionName = "<threw " + ex.GetType().Name + ">"; }

            try
            {
                var main = Hero.MainHero;
                if (main != null)
                {
                    var party = main.PartyBelongedTo;
                    if (party != null)
                    {
                        var cs = party.CurrentSettlement;
                        if (cs != null) partySettle = cs.StringId ?? "(no-id)";
                        else partySettle = "(no CurrentSettlement)";
                    }
                    else partySettle = "(no PartyBelongedTo)";
                }
            }
            catch (Exception ex)
            { partySettle = "<threw " + ex.GetType().Name + ">"; }

            try
            {
                var cs = Settlement.CurrentSettlement;
                if (cs != null) currentSettle = cs.StringId ?? "(no-id)";
            }
            catch (Exception ex)
            { currentSettle = "<threw " + ex.GetType().Name + ">"; }

            try
            {
                var c = Campaign.Current;
                if (c != null) gameStarted = c.GameStarted.ToString();
            }
            catch (Exception ex)
            { gameStarted = "<threw " + ex.GetType().Name + ">"; }

            SafeWrite("SAVEDIAG: " + phase + " STATE"
                + " | PlayerEncounter=" + encName
                + " | LocationEncounter=" + locEncName
                + " | Mission=" + missionName + " mode=" + missionMode
                + " | partyCurrentSettlement=" + partySettle
                + " | Settlement.CurrentSettlement=" + currentSettle
                + " | Campaign.GameStarted=" + gameStarted);
        }
    }
}
